services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16-oss
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monitoring
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: always

  grafana:
    image: grafana/grafana:main
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - timescaledb
    restart: always

  pgadmin:
    image: dpage/pgadmin4:8.12.0
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - timescaledb
    restart: always

volumes:
  pgadmin_data:
  timescaledb_data:
  grafana_data:
